#!/bin/sh
ATMSRFOUTLOC="/glade/u/home/nforcone/MidwestVarRes"
atmName="midwest-06-16-2025_edit22"
atmGridName=/glade/u/home/nforcone/MidwestVarRes/midwest-06-16-2025_edit22_np4_SCRIP.nc
SCRATCHDIR=/glade/derecho/scratch/nforcone
MACHINE="NCAR"

cd /glade/u/home/nforcone/vr-cesm-toolkit/gen_atmsrf/

set +e
date
ncl gen_se_mkatmsrf_from_se.ncl \
  'dstName="'${atmName}'"' \
  'dstGridDir="'${atmGridName%/*}/'"' \
  'dstGridFile="'${atmGridName##*/}'"' \
  'atmsrfDir="'${ATMSRFOUTLOC}'"' \
  'wgtFileDir="'${SCRATCHDIR}'"' \
  'MACHINE="'${MACHINE}'"'
date
set -e
