#!/bin/sh
module load conda
conda activate npl-2025a

cd /glade/derecho/scratch/nforcone/ctsm5.3.002/tools/mksurfdata_esmf
RES=midwest-06-16-2025_edit22
START=2020
END=2021
MESH='/glade/u/home/nforcone/MidwestVarRes/midwest-06-16-2025_edit22_ESMF.nc'
NX=316010
NY=1

./gen_mksurfdata_namelist --res $RES --start-year $START --end-year $END --model-mesh $MESH --model-mesh-nx $NX --model-mesh-ny $NY
