#!/bin/sh
echo Generate a SCRIP file...

EXODUSPATH="/glade/u/home/nforcone/squadgen/"
EXODUSNAME="midwest-06-16-2025_edit22.g"

# go to directory
cd $VRTOOLKIT
cd generate_SE_GLL_scrip

[ -f ./Gen_ControlVolumes.exe ] || make

# Inject Exodus file into namelist
sed -i.bak -e "s|^\s*GridPath\s*=.*|  GridPath = '${EXODUSPATH}'|" \
           -e "s|^\s*GridName\s*=.*|  GridName = '${EXODUSNAME}'|" input.nl

# Call program
./Gen_ControlVolumes.exe input.nl
