#!/bin/sh
CESM_DIR=/glade/u/home/nforcone/CAM_6_4_025_20240829
COMPSET=FADIAB
MACHINE=derecho
RES=ne0MIDWESTne30x32_ne0MIDWESTne30x32
PECOUNT=512
CASE_PATH=~/CAM_6_4_025_20240829_cases/CAM_6_4_025_20240829_topo_bw_dry_ne0MIDWESTne30x32_ne0MIDWESTne30x32
PROJ=UMIC0107

$CESM_DIR/cime/scripts/create_newcase --compset $COMPSET --mach $MACHINE --res $RES --pecount $PECOUNT --case $CASE_PATH --run-unsupported --project $PROJ

cd $CASE_PATH

./xmlchange STOP_OPTION=ndays
./xmlchange STOP_N=10
./xmlchange RESUBMIT=0
./xmlchange JOB_WALLCLOCK_TIME=01:00:00
./xmlchange DOUT_S='FALSE'
./xmlchange --file env_build.xml --id CAM_CONFIG_OPTS --val "--phys adiabatic --analytic_ic"
